#pragma once


#define TAPPING_TERM 220
#define QUICK_TAP_TERM 0
#define PERMISSIVE_HOLD


// Auto Shift
#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
// #define AUTO_SHIFT_NO_SETUP
# define AUTO_SHIFT_MODIFIERS

#define RETRO_SHIFT 500

// CAPS WORD
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_INVERT_ON_SHIFT
